/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/oQNbaDaOj51
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogClose } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { ThemeColorPicker } from "./theme-color-picker"
import { JSX, SVGProps, useContext } from "react"
import { ThemeColorContext  } from "@/lib/theme-color";
export function Modal() {
  
  const {color, setColor} = useContext(ThemeColorContext);
  const {color2, setColor2} = useContext(ThemeColorContext);
  const {colorText, setColorText} = useContext(ThemeColorContext);
  const {colorText2, setColorText2} = useContext(ThemeColorContext);
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button style={{backgroundColor: `rgba(${color2?.r ?? 0}, ${color2?.g ?? 0}, ${color2?.b ?? 0}, ${color2?.a/100 ?? 0})`}}>Open Color Picker</Button>
      </DialogTrigger>
      <DialogContent className="w-full">
        <DialogHeader>
          <DialogTitle>Pick Theme Colors</DialogTitle>
          
        </DialogHeader>
        <div className="py-6">
          <ThemeColorPicker />
        </div>
      </DialogContent>
    </Dialog>
  )
}

function XIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
